### ISSUE TITLE
Get-Credential does not work for smart cards with multiple certificates.

### ISSUE THREAD

**Issue by milesgratz** [bongiovimatthew-microsoft/pscredentialWithCert#1]
Hi - 

### Overview 

There is a limitation in PowerShell for the `Get-Credential` cmdlet that only allows you to use the first certificate on the smartcard. Information here: [PowerShell/PowerShell/#4670](https://github.com/PowerShell/PowerShell/issues/4670). Hopefully this will be fixed in PS 6.1, but unfortunately our production servers are years away from supporting that version. Long story short, is it possible to create a smartcard PSCredential object within PowerShell and .NET? Or is it required to use C# ? 

### Expected behavior

Ability to choose a specific certificate on smartcard with PowerShell `Get-Credential` native cmdlet.

### Actual behavior

PowerShell `Get-Credential` native cmdlet only supports the first certificate on smartcard. 

![expected_behavior](https://user-images.githubusercontent.com/17114534/39899875-e087547c-5483-11e8-894b-42125fc1af0f.png)

### Steps to reproduce 

Create a virtual or physical smartcard with multiple certificates. Try to select a specific certificate using PowerShell `Get-Credential` native cmdlet.

**Comment by bongiovimatthew-microsoft** [comment]
@milesgratz, are you able to read the certificate thumbprints from the smartcard directly? If you are able to locate the same cert in the User/My cert store, you can create a PSCredential object yourself (see `MarshalFlow(string thumbprint)` in  [Program.cs](https://github.com/bongiovimatthew-microsoft/pscredentialWithCert/blob/master/SmartcardLogon/Program.cs))

**Comment by bongiovimatthew-microsoft** [comment]
Based on the PowerShell bug you linked, it looks like you have code that will let you select the certificate you want: 

`Add-Type -AssemblyName System.Security
$ValidCerts = [System.Security.Cryptography.X509Certificates.X509Certificate2[]](dir Cert:\CurrentUser\My)
$Cert = [System.Security.Cryptography.X509Certificates.X509Certificate2UI]::SelectfromCollection($ValidCerts,'Choose a certificate','Choose a certificate',0)`

The $Cert object you get back has a Thumbprint property. Try passing that to `MarshalFlow(string thumbprint)` mentioned above. The function is for demo purposes, so you will have to adjust the function to return the `psCreds` object (`psCreds = new PSCredential(certBlobForUsername, new SecureString());`)

**Comment by jimmy58663** [comment]
@bongiovimatthew-microsoft I was able to utilize your code in PowerShell to create and return the credential as you stated for any certificate on a smart card. If I screwed up on how I am utilizing the copyright let me know. I would like to post this to the PowerShell issue as well. @milesgratz below is the code I am using to accomplish this.

    Function Get-SmartCardCred{
    <#
    .SYNOPSIS
    Get certificate credentials from the user's certificate store.

    .DESCRIPTION
    Returns a PSCredential object of the user's selected certificate.

    .EXAMPLE
    Get-SmartCardCred
    UserName                                           Password
    --------                                           --------
    @@BVkEYkWiqJgd2d9xz3-5BiHs1cAN System.Security.SecureString

    .EXAMPLE
    $Cred = Get-SmartCardCred

    .OUTPUTS
    [System.Management.Automation.PSCredential]

    .NOTES
    Author: Joshua Chase
    Last Modified: 01 August 2018
    C# code used from https://github.com/bongiovimatthew-microsoft/pscredentialWithCert
    #>
    [cmdletbinding()]
    param()

        $SmartCardCode = @"
    // Copyright (c) Microsoft Corporation. All rights reserved.
    // Licensed under the MIT License.

    using System;
    using System.Management.Automation;
    using System.Runtime.InteropServices;
    using System.Security;
    using System.Security.Cryptography.X509Certificates;


    namespace SmartCardLogon{

        static class NativeMethods
        {

            public enum CRED_MARSHAL_TYPE
            {
                CertCredential = 1,
                UsernameTargetCredential
            }

            [StructLayout(LayoutKind.Sequential)]
            internal struct CERT_CREDENTIAL_INFO
            {
                public uint cbSize;
                [MarshalAs(UnmanagedType.ByValArray, SizeConst = 20)]
                public byte[] rgbHashOfCert;
            }

            [DllImport("advapi32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
            public static extern bool CredMarshalCredential(
                CRED_MARSHAL_TYPE CredType,
                IntPtr Credential,
                out IntPtr MarshaledCredential
            );

            [DllImport("advapi32.dll", SetLastError = true)]
            public static extern bool CredFree([In] IntPtr buffer);

        }

        public class Certificate
        {

            public static PSCredential MarshalFlow(string thumbprint, SecureString pin)
            {
                //
                // Set up the data struct
                //
                NativeMethods.CERT_CREDENTIAL_INFO certInfo = new NativeMethods.CERT_CREDENTIAL_INFO();
                certInfo.cbSize = (uint)Marshal.SizeOf(typeof(NativeMethods.CERT_CREDENTIAL_INFO));

                //
                // Locate the certificate in the certificate store 
                //
                X509Certificate2 certCredential = new X509Certificate2();
                X509Store userMyStore = new X509Store(StoreName.My, StoreLocation.CurrentUser);
                userMyStore.Open(OpenFlags.ReadOnly);
                X509Certificate2Collection certsReturned = userMyStore.Certificates.Find(X509FindType.FindByThumbprint, thumbprint, false);
                userMyStore.Close();

                if (certsReturned.Count == 0)
                {
                    throw new Exception("Unable to find the specified certificate.");
                }

                //
                // Marshal the certificate 
                //
                certCredential = certsReturned[0];
                certInfo.rgbHashOfCert = certCredential.GetCertHash();
                int size = Marshal.SizeOf(certInfo);
                IntPtr pCertInfo = Marshal.AllocHGlobal(size);
                Marshal.StructureToPtr(certInfo, pCertInfo, false);
                IntPtr marshaledCredential = IntPtr.Zero;
                bool result = NativeMethods.CredMarshalCredential(NativeMethods.CRED_MARSHAL_TYPE.CertCredential, pCertInfo, out marshaledCredential);

                string certBlobForUsername = null;
                PSCredential psCreds = null;

                if (result)
                {
                    certBlobForUsername = Marshal.PtrToStringUni(marshaledCredential);
                    psCreds = new PSCredential(certBlobForUsername, pin);
                }

                Marshal.FreeHGlobal(pCertInfo);
                if (marshaledCredential != IntPtr.Zero)
                {
                    NativeMethods.CredFree(marshaledCredential);
                }
                
                return psCreds;
            }
        }
    }
    "@

        Add-Type -TypeDefinition $SmartCardCode -Language CSharp
        Add-Type -AssemblyName System.Security

        $ValidCerts = [System.Security.Cryptography.X509Certificates.X509Certificate2[]](Get-ChildItem 'Cert:\CurrentUser\My')
        $Cert = [System.Security.Cryptography.X509Certificates.X509Certificate2UI]::SelectFromCollection($ValidCerts, 'Choose a certificate', 'Choose a certificate', 0)

        $Pin = Read-Host "Enter your PIN: " -AsSecureString

        Write-Output ([SmartCardLogon.Certificate]::MarshalFlow($Cert.Thumbprint, $Pin))
    }

**Comment by bongiovimatthew-microsoft** [comment]
@jimmy58663, that code looks great! Would you mind if we maintained a copy of the it in this repo? If you fork this repo and do a pull request to my master, it will show up properly credited to you.

**Comment by jimmy58663** [comment]
@bongiovimatthew-microsoft, it is fine that you keep the code in the repo. You can just add it, I don't need the credit. Thanks for your help though because your code is doing all the heavy lifting.

**Comment by bongiovimatthew-microsoft** [comment]
Sounds good, I updated the repo to include this code. Thanks again!

**Comment by jokezone** [comment]
Great work guys! Is it possible to package up a username hint with the PSCredential object, similar to the Remote Desktop and LogonUI prompts in the below screenshots? Having support for username hint smart card mapping in only some of the authentication methods is very annoying.

Remote Desktop:
![image](https://user-images.githubusercontent.com/21342194/45107330-86f11980-b139-11e8-8baf-370673bd94fc.png)

LogonUI:
![image](https://user-images.githubusercontent.com/21342194/45107801-0a5f3a80-b13b-11e8-927e-e9797b969ef6.png)

**Comment by bongiovimatthew-microsoft** [comment]
Thanks @jokezone, it looks like as of now, the command line Get-Credential prompt doesn't support the username hint field. The code [here](https://github.com/bongiovimatthew-microsoft/pscredentialWithCert/blob/master/PowerShell/ReadFromAnySmartcard.ps1) sidesteps this a bit by letting you pick the specific cert you want from a different UI prompt, and then collecting the PIN from the commandline. 

Depending on what your end-goal is, you could do something similar with the username hint. In the code linked above, at the end you could add another line similar to the PIN collection line, which reads the username hint. (You could also use the `$host.ui.Prompt()` command). 

Unfortunately there is no way right now to wrap the username hint into the PSCredential object, but your code could return your own PSObject that has the PSCredential and the UsernameHint as fields. Then, whatever code is consuming your PSCredential object would have to be modified to piece apart your new object and make the appropriate Windows API calls with the PSCredential and Username fields marshaled appropriately.

**Comment by GeorgeChiuTheHartford** [comment]
Thanks for the provided Get-SmartCardCred script block, it works well for on-prem, however, it does not work for Azure or Office 365 cmdlet such as Connect-AzureAD and Connect-MsolService.   Does anyone know what's the solution ?

**Comment by Christian-Martinez1** [comment]
Hey guys, trying to use this so that I can automate some reporting that needs to be ran under admin credentials and our organization uses smartcards. As it would ideally be automated, I would like to define the certificate by thumbprint and hardcode the certificate path as well as the PIN as below:

`$Cert = [System.Security.Cryptography.X509Certificates.X509Certificate2[]](Get-ChildItem Cert:\CurrentUser\My\5700154xxxxxxxxxxxxxxxxxxxxxxxxxxx)
$Pin = ConvertTo-SecureString 'xxxxxx' -AsPlainText -Force`

However I am getting the following error: 
Start-Process : This command cannot be run due to the error: The user name or password is incorrect.

When I output $cert it does output the correct certificate properties so I am quite confused on why I am getting incorrect username/password errors, would anyone be able to help?

Regards,

Chris

**Comment by jimmy58663** [comment]
@Christian-Martinez1 The error you are seeing is due to the way Start-Process handles PScredential objects. A fix for this is to manually create the process from .Net calls. The below example launches PowerShell with those credentials after which you can manually run any command as that account.

```
$Cred = Get-SmartCardCred

$StartInfo = New-Object System.Diagnostics.ProcessStartInfo
$StartInfo.FileName = 'powershell.exe'
$StartInfo.UseShellExecute = $false
$StartInfo.UserName = $Cred.Username
$StartInfo.Password = $Cred.Password
$StartInfo.Arguments = 'Start-Process powershell'
$StartInfo.WorkingDirectory = $env:windir

$Process = New-Object System.Diagnostics.Process
$Process.StartInfo = $StartInfo
$Process.Start()

$Cred = $null
```

If you need it run as an elevated prompt, you need to also add `$StartInfo.Verb = 'runas'`. This repository does not seem to be maintained by the original author anymore so I do have a fork that is a bit updated at https://github.com/jimmy58663/pscredentialWithCert. I recommend in the future to also open a new issue rather than commenting on a closed one.

Lastly, I highly advise you do not utilize `$Pin = ConvertTo-SecureString 'xxxxxx' -AsPlainText -Force`. If your organization is utilizing script block logging or transcription, your ConvertTo-SecureString will provide your PIN in plaintext in the Windows Event Logs or wherever the transcription is being saved.
